# On utilise une image officielle de Node.js 14 basée sur Alpine Linux, une distribution légère
FROM node:14-alpine

# On définit le dossier de travail de l'application dans le conteneur
WORKDIR /app

# On copie le fichier package.json dans le WORKDIR
COPY package*.json ./

# On installe les dépendances de production de l'application
RUN npm install --production

# On copie le code source de l'application dans le WORKDIR
COPY . .

# On définit la commande à exécuter lorsque le conteneur sera démarré
CMD ["npm", "start"]